global:
  scrape_interval:     15s
  evaluation_interval: 15s

# scrape_configs:
  # - job_name: 'otel-collector'
    # static_configs:
      # - targets: ['otel-collector:9464']
  # - job_name: node
    # static_configs:
      # - targets: ['localhost:9100']
  # - job_name: "api-contagem"
    # static_configs:
      # - targets: ["host.docker.internal:5001"]
  # - job_name: "api-orquestracao"
    # static_configs:
      # - targets: ["host.docker.internal:5000"]
      
scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node_exporter:9100']
  - job_name: 'otel-collector'
    scrape_interval: 5s
    static_configs:
      - targets: ['otel-collector:8889', 'otel-collector:8888']